task: jar_infeasible
seed: 42
device: cuda
num_workers: 0
lr: 0.0001
grad_clip: 5.0
obs_horizon: 1
action_horizon: 8
pred_horizon: 8
use_ee_data: true
torch_compile: false
train_demo_ids: []
val_demo_ids: []
human_train_demo_ids:
- demo00000
- demo00001
- demo00002
- demo00003
- demo00004
- demo00005
- demo00006
- demo00007
- demo00008
- demo00009
- demo00010
- demo00011
- demo00012
- demo00013
- demo00014
- demo00015
- demo00016
- demo00017
- demo00018
- demo00019
- demo00020
- demo00021
- demo00022
- demo00023
- demo00024
- demo00025
- demo00026
- demo00027
- demo00028
- demo00029
- demo00030
- demo00031
- demo00032
- demo00033
- demo00034
- demo00035
- demo00036
- demo00037
- demo00038
- demo00039
- demo00040
- demo00041
- demo00042
- demo00043
- demo00044
- demo00045
- demo00046
- demo00047
human_val_demo_ids:
- demo00048
- demo00049
- demo00050
- demo00051
run_name: policy_jar_v1
mode: naive
epochs: 150
steps_per_epoch: 200
max_val_batches: 30
batch_size: 128
balanced_sampling_weights: null
integrate_classifier: false
threshold: 0.5
num_train_timesteps: 101
grasp_dim_robot_only: false
flip_oversample_factor: 3.0
use_interferer: true
interferer_oversample_factor: 1.0
vis_force_admission: false
interferer_neg_dropout: 0.0
neg_dropout_scope: closed
use_wandb: true
wandb_project: x-diffusion-hrc
wandb_run_name: jar-policy-v1
