task: green_lego
seed: 42
device: cuda
num_workers: 0
lr: 0.0001
grad_clip: 5.0
obs_horizon: 1
action_horizon: 8
pred_horizon: 8
use_ee_data: true
torch_compile: false
train_demo_ids:
- demo00000
- demo00001
- demo00002
- demo00003
- demo00004
val_demo_ids:
- demo00005
human_train_demo_ids:
- demo00000
- demo00001
- demo00002
- demo00003
- demo00004
- demo00005
- demo00006
- demo00007
- demo00008
- demo00009
- demo00010
- demo00011
- demo00012
- demo00013
- demo00014
- demo00015
- demo00016
- demo00017
- demo00018
- demo00019
- demo00020
- demo00021
- demo00022
- demo00023
- demo00024
- demo00025
- demo00026
- demo00027
human_val_demo_ids:
- demo00028
- demo00029
run_name: smoke_classifier_green
epochs: 3
steps_per_epoch: 8
max_val_batches: 4
batch_size: 32
balanced_sampling_weights:
- 0.5
- 0.5
num_train_timesteps: 101
add_noise_to_sample: true
add_noise_to_state_cond: true
threshold: 0.5
